### ISSUE TITLE
Fai attenzione a chiudere i tag 

### ISSUE THREAD

**Issue by robertoperuzzo** [ilija-derajic-2003/animali-del-bosco#4]
`<img src="img/scoiattolo.jpg" alt="scoiattolo"` qui hai lasciato aperto il tag img, basta aggiunger > alla fine `<img src="img/scoiattolo.jpg" alt="scoiattolo">`

**Comment by ilija-derajic-2003** [comment]
sono stati sistemati i tag di chiusura
